"""user_id removed from recipe table

Revision ID: 6a3a02fcf411
Revises: eb7d733aa7ff
Create Date: 2023-05-15 16:32:16.154188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3a02fcf411'
down_revision = 'eb7d733aa7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('recipes_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('recipes_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
